In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [4]:
df.shape

(50000, 2)

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.shape

(49582, 2)

In [15]:
df.columns

Index(['review', 'sentiment'], dtype='object')

# Pre-Processing

## Converting into Lowercase

In [17]:
df["review"] = df["review"].str.lower()

## Removing URLs

In [18]:
import re

In [19]:
def remove_urls(text):
    text = re.sub(r"http\S+" , "", text)  
    return text
    
df["review"] = df["review"].apply(remove_urls)

## Removing Punctuations

In [20]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text)
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [21]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

## Removing HTML

In [22]:
def remove_html(text):
    text = re.sub(r"<.*?>" , "", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [23]:
df.head(10)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive
5  probably my alltime favorite movie a story of ...  positive
6  i sure would like to see a resurrection of a u...  positive
7  this show was an amazing fresh  innovative ide...  negative
8  encouraged by the positive comments about this...  negative
9  if you like original gut wrenching laughter yo...  positive

## Removing Stopwords

In [16]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\akibz\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\akibz\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\akibz\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [24]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [28]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word,"")
    return text

df["review"] = df["review"].apply(remove_stopwords)

In [29]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

## Stemming

In [30]:
from nltk.stem import PorterStemmer

In [37]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)
df["review"] = df["review"].apply(stemming)

In [38]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

## Encoding

In [39]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [40]:
y = df["sentiment"]

In [41]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

## Vectorization

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

x = tf.fit_transform(df["review"])

# Datast and Data Loaders

In [43]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [44]:
x_train.shape

(39665, 5000)

In [45]:
x_test.shape

(9917, 5000)

In [46]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [47]:
x_train = x_train.toarray()
x_test = x_test.toarray()

In [48]:
train_set = TensorDataset(
    torch.from_numpy(x_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(x_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [49]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

# Building RNN

In [50]:
import torch.nn as nn
import torch.optim as optim

In [51]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0) 
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [52]:
input_size = x_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

# RNN Training

In [53]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction
        
        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) 

        loss = criterion(outputs, yb) # compute loss
        loss.backward() 
        optimizer.step() 

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.2651696801185608
epoch = 2/10 and loss = 0.1651306301355362
epoch = 3/10 and loss = 0.27858805656433105
epoch = 4/10 and loss = 0.13752686977386475
epoch = 5/10 and loss = 0.211378276348114
epoch = 6/10 and loss = 0.21639037132263184
epoch = 7/10 and loss = 0.2502916753292084
epoch = 8/10 and loss = 0.233427956700325
epoch = 9/10 and loss = 0.32648810744285583
epoch = 10/10 and loss = 0.1973009556531906

# Evaluation

In [54]:
model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0
    
    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 85.6206514066754